services:
  - type: worker
    name: bot-cierre-1217
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
